paths:
  input: "input"
  output: "outputs"
  
colors:
  purple: [[120, 80, 50], [150, 255, 255]]
  cyan: [[85, 150, 150], [100, 255, 255]]
  white: [[0, 0, 250], [180, 15, 255]]
  green_light: [[85, 118, 118], [95, 138, 138]]
  green_dark: [[55, 245, 186], [65, 255, 206]]
  gray_dark: [[0, 0, 187], [180, 5, 197]]
  yellow: [[20, 100, 100], [40, 255, 255]]
  red: [[0, 150, 150], [10, 255, 255]]

export:
  excel_filename: "ocr_results.xlsx"